/**
 * @fileoverview Auto-generated PagesCMS types from .pages.yml
 *
 * Generated by: scripts/generate-pages-cms-types.js
 * Do not edit manually - regenerate using: bun scripts/generate-pages-cms-types.js
 *
 * These types represent data validated by PagesCMS schema (.pages.yml).
 * Fields marked as required: true in the schema are non-optional.
 * Use these in JSDoc annotations to leverage validation guarantees.
 */

/**
 * @typedef {Object} PagesCMSEleventyNavigation
 * @property {string} ?key - 
 * @property {number} ?order - 
 */
export interface PagesCMSEleventyNavigation {
  key?: string;
  order?: number;
}

/**
 * @typedef {Object} PagesCMSFaq
 * @property {string} question - Question
 * @property {string} answer - Answer
 */
export interface PagesCMSFaq {
  question: string;
  answer: string;
}

/**
 * @typedef {Object} PagesCMSOption
 * @property {string} name - Option Name
 * @property {number} ?max_quantity - Max Quantity
 * @property {number} unit_price - Unit Price (£)
 * @property {number} ?days - Days (for hire products)
 */
export interface PagesCMSOption {
  name: string;
  max_quantity?: number;
  unit_price: number;
  days?: number;
}

/**
 * @typedef {Object} PagesCMSFilterAttribute
 * @property {string} name - Name
 * @property {string} value - Value
 */
export interface PagesCMSFilterAttribute {
  name: string;
  value: string;
}

/**
 * @typedef {Object} PagesCMSSpec
 * @property {string} name - Name
 * @property {string} value - Value
 */
export interface PagesCMSSpec {
  name: string;
  value: string;
}

/**
 * @typedef {Object} PagesCMSTab
 * @property {string} title - Title
 * @property {string} ?image - Image
 * @property {string} body - Body
 */
export interface PagesCMSTab {
  title: string;
  image?: string;
  body: string;
}

/**
 * @typedef {Object} PagesCMSOpeningTime
 * @property {string} day - Day
 * @property {string} hours - Hours
 */
export interface PagesCMSOpeningTime {
  day: string;
  hours: string;
}

/**
 * @typedef {Object} PagesCMSSocial
 * @property {string} ?Github - Github
 * @property {string} ?Forgejo - Forgejo
 * @property {string} ?Facebook - Facebook
 * @property {string} ?Instagram - Instagram
 * @property {string} ?TikTok - TikTok
 * @property {string} ?Google - Google
 * @property {string} ?WhatsApp - WhatsApp
 * @property {string} ?RSS - RSS
 */
export interface PagesCMSSocial {
  Github?: string;
  Forgejo?: string;
  Facebook?: string;
  Instagram?: string;
  TikTok?: string;
  Google?: string;
  WhatsApp?: string;
  RSS?: string;
}

/**
 * @typedef {Object} PagesCMSOrganization
 * @property {string} ?description - Organization Description
 * @property {string} ?legalName - Legal Name
 * @property {string} ?foundingDate - Founding Date
 * @property {Record<string, unknown>} ?founders - Founders
 * @property {Record<string, unknown>} ?address - Address
 * @property {Record<string, unknown>} ?contactPoint - Contact Points
 */
export interface PagesCMSOrganization {
  description?: string;
  legalName?: string;
  foundingDate?: string;
  founders?: Record<string, unknown>;
  address?: Record<string, unknown>;
  contactPoint?: Record<string, unknown>;
}

/**
 * @typedef {Object} PagesCMSImage
 * @property {string} ?path - Image
 * @property {string} ?alt - Alt Text
 */
export interface PagesCMSImage {
  path?: string;
  alt?: string;
}

