import { withTestSite } from "#test/test-site-factory.js";
import { createTestRunner, expectTrue } from "#test/test-utils.js";

// Test the actual feed output using isolated test sites
// Each test creates its own Eleventy build with specific content

const testCases = [
  // --- File Generation ---
  {
    name: "feed-xml-exists",
    description: "Feed XML file is generated by the build",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "news/2024-01-01-test-post.md",
              frontmatter: { title: "Test Post" },
              content: "Test content for feed.",
            },
          ],
        },
        (site) => {
          expectTrue(
            site.hasOutput("feed.xml"),
            "feed.xml should exist in _site",
          );
        },
      );
    },
  },
  {
    name: "feed-xml-valid-atom",
    description: "Feed is valid Atom XML",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "news/2024-01-01-test-post.md",
              frontmatter: { title: "Test Post" },
              content: "Test content.",
            },
          ],
        },
        (site) => {
          const content = site.getOutput("feed.xml");

          expectTrue(
            content.includes('<?xml version="1.0"'),
            "Should have XML declaration",
          );
          expectTrue(
            content.includes('<feed xmlns="http://www.w3.org/2005/Atom"'),
            "Should be an Atom feed",
          );
          expectTrue(
            content.includes("</feed>"),
            "Should have closing feed tag",
          );
        },
      );
    },
  },
  {
    name: "feed-has-required-elements",
    description: "Feed contains required Atom elements",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "news/2024-01-01-test-post.md",
              frontmatter: { title: "Test Post" },
              content: "Test content.",
            },
          ],
          config: { site_name: "Test Site" },
        },
        (site) => {
          const content = site.getOutput("feed.xml");

          expectTrue(content.includes("<title>"), "Should have title element");
          expectTrue(content.includes("<id>"), "Should have id element");
          expectTrue(
            content.includes("<updated>"),
            "Should have updated element",
          );
          expectTrue(
            content.includes("<author>"),
            "Should have author element",
          );
        },
      );
    },
  },

  // --- Entry Structure ---
  {
    name: "feed-has-entries",
    description: "Feed contains entry elements for blog posts",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "news/2024-01-01-first-post.md",
              frontmatter: { title: "First Post" },
              content: "First post content.",
            },
            {
              path: "news/2024-01-02-second-post.md",
              frontmatter: { title: "Second Post" },
              content: "Second post content.",
            },
          ],
        },
        (site) => {
          const content = site.getOutput("feed.xml");

          expectTrue(content.includes("<entry>"), "Should have entry elements");
          expectTrue(
            content.includes("</entry>"),
            "Should have closing entry tags",
          );
          expectTrue(
            content.includes("First Post"),
            "Should include first post title",
          );
          expectTrue(
            content.includes("Second Post"),
            "Should include second post title",
          );
        },
      );
    },
  },
  {
    name: "feed-entries-have-content",
    description: "Feed entries have content with absolute URLs",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "news/2024-01-01-test-post.md",
              frontmatter: { title: "Test Post" },
              content: "Check out [our homepage](/) for more info.",
            },
          ],
        },
        (site) => {
          const content = site.getOutput("feed.xml");

          expectTrue(
            content.includes('<content type="html">'),
            "Entries should have HTML content",
          );
          // Links in content should be absolute (transformed by htmlBase plugin)
          expectTrue(
            content.includes('href="https://'),
            "Links should be absolute URLs",
          );
        },
      );
    },
  },
  {
    name: "feed-has-self-link",
    description: "Feed has self-referencing link",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "news/2024-01-01-test-post.md",
              frontmatter: { title: "Test Post" },
              content: "Test content.",
            },
          ],
        },
        (site) => {
          const content = site.getOutput("feed.xml");

          expectTrue(
            content.includes('rel="self"'),
            "Should have self-referencing link",
          );
          expectTrue(
            content.includes("/feed.xml"),
            "Self link should point to feed.xml",
          );
        },
      );
    },
  },

  // --- Edge Cases ---
  {
    name: "feed-with-no-posts",
    description: "Feed is generated even when there are no blog posts",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "pages/about.md",
              frontmatter: { title: "About", layout: "page" },
              content: "# About us",
            },
          ],
        },
        (site) => {
          expectTrue(site.hasOutput("feed.xml"), "feed.xml should exist");
          const feed = site.getOutput("feed.xml");
          expectTrue(
            feed.includes('<feed xmlns="http://www.w3.org/2005/Atom"'),
            "Should be valid Atom feed",
          );
          // With no posts, there should be no entries
          expectTrue(
            !feed.includes("<entry>"),
            "Empty feed should have no entries",
          );
        },
      );
    },
  },
  {
    name: "feed-uses-site-name",
    description: "Feed title matches configured site name",
    asyncTest: async () => {
      await withTestSite(
        {
          dataFiles: [
            {
              filename: "site.json",
              data: {
                name: "Test Blog Name",
                url: "https://test.example.com",
                description: "Test site",
              },
            },
          ],
          files: [
            {
              path: "news/hello.md",
              frontmatter: { title: "Hello World" },
              content: "First post",
            },
          ],
        },
        (site) => {
          const feed = site.getOutput("feed.xml");
          expectTrue(
            feed.includes("<title>Test Blog Name</title>"),
            "Feed title should match site name config",
          );
        },
      );
    },
  },
  {
    name: "feed-handles-special-characters",
    description: "Feed is valid XML with special characters in titles",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "news/special.md",
              frontmatter: { title: "Tom and Jerry's Adventure" },
              content: "Special chars test",
            },
          ],
        },
        (site) => {
          const feed = site.getOutput("feed.xml");
          // Feed should be valid XML and contain the entry
          expectTrue(
            feed.includes("<entry>"),
            "Feed should have entry element",
          );
          expectTrue(
            feed.includes("Tom and Jerry"),
            "Entry title should contain expected text",
          );
          // Apostrophe should be handled (either escaped or in CDATA)
          expectTrue(
            feed.includes("Jerry's") || feed.includes("Jerry&#39;s"),
            "Apostrophe should be handled in title",
          );
        },
      );
    },
  },
  {
    name: "feed-entries-ordered-newest-first",
    description: "Feed entries are ordered with most recent first",
    asyncTest: async () => {
      await withTestSite(
        {
          files: [
            {
              path: "news/2024-01-01-older.md",
              frontmatter: { title: "Older Post" },
              content: "First",
            },
            {
              path: "news/2024-06-15-newer.md",
              frontmatter: { title: "Newer Post" },
              content: "Second",
            },
          ],
        },
        (site) => {
          const feed = site.getOutput("feed.xml");
          const olderPos = feed.indexOf("Older Post");
          const newerPos = feed.indexOf("Newer Post");

          expectTrue(olderPos > 0, "Should contain Older Post");
          expectTrue(newerPos > 0, "Should contain Newer Post");
          expectTrue(
            newerPos < olderPos,
            "Newer post should appear before older post in feed",
          );
        },
      );
    },
  },
];

export default createTestRunner("feed", testCases);
