import { createTestRunner, expectTrue, fs, path } from "#test/test-utils.js";

// Test the actual feed output from the real Eleventy build
// instead of mocking Eleventy config and testing third-party functions

const testCases = [
  {
    name: "feed-xml-exists",
    description: "Feed XML file is generated by the build",
    test: () => {
      const feedPath = path.join(process.cwd(), "_site/feed.xml");
      expectTrue(fs.existsSync(feedPath), "feed.xml should exist in _site");
    },
  },
  {
    name: "feed-xml-valid-atom",
    description: "Feed is valid Atom XML",
    test: () => {
      const feedPath = path.join(process.cwd(), "_site/feed.xml");
      const content = fs.readFileSync(feedPath, "utf-8");

      expectTrue(
        content.includes('<?xml version="1.0"'),
        "Should have XML declaration",
      );
      expectTrue(
        content.includes('<feed xmlns="http://www.w3.org/2005/Atom"'),
        "Should be an Atom feed",
      );
      expectTrue(content.includes("</feed>"), "Should have closing feed tag");
    },
  },
  {
    name: "feed-has-required-elements",
    description: "Feed contains required Atom elements",
    test: () => {
      const feedPath = path.join(process.cwd(), "_site/feed.xml");
      const content = fs.readFileSync(feedPath, "utf-8");

      expectTrue(content.includes("<title>"), "Should have title element");
      expectTrue(content.includes("<id>"), "Should have id element");
      expectTrue(content.includes("<updated>"), "Should have updated element");
      expectTrue(content.includes("<author>"), "Should have author element");
    },
  },
  {
    name: "feed-has-entries",
    description: "Feed contains entry elements for blog posts",
    test: () => {
      const feedPath = path.join(process.cwd(), "_site/feed.xml");
      const content = fs.readFileSync(feedPath, "utf-8");

      expectTrue(content.includes("<entry>"), "Should have entry elements");
      expectTrue(
        content.includes("</entry>"),
        "Should have closing entry tags",
      );
    },
  },
  {
    name: "feed-entries-have-content",
    description: "Feed entries have content with absolute URLs",
    test: () => {
      const feedPath = path.join(process.cwd(), "_site/feed.xml");
      const content = fs.readFileSync(feedPath, "utf-8");

      expectTrue(
        content.includes('<content type="html">'),
        "Entries should have HTML content",
      );
      // Links in content should be absolute (transformed by htmlBase plugin)
      expectTrue(
        content.includes('href="https://'),
        "Links should be absolute URLs",
      );
    },
  },
  {
    name: "feed-has-self-link",
    description: "Feed has self-referencing link",
    test: () => {
      const feedPath = path.join(process.cwd(), "_site/feed.xml");
      const content = fs.readFileSync(feedPath, "utf-8");

      expectTrue(
        content.includes('rel="self"'),
        "Should have self-referencing link",
      );
      expectTrue(
        content.includes("/feed.xml"),
        "Self link should point to feed.xml",
      );
    },
  },
];

export default createTestRunner("feed", testCases);
