import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { createTestSite } from "#test/test-site-factory.js";

// Test the actual feed output using isolated test sites
// Tests are grouped to minimize builds while maintaining test isolation

describe("feed", () => {
  // --- Comprehensive test site (covers most feed tests) ---
  // Single build for tests that can share the same content
  describe("comprehensive site", () => {
    let site;
    let feed;

    beforeAll(async () => {
      site = await createTestSite({
        dataFiles: [
          {
            filename: "site.json",
            data: {
              name: "Test Blog Name",
              url: "https://test.example.com",
              description: "Test site",
            },
          },
        ],
        files: [
          {
            path: "news/2024-01-01-older.md",
            frontmatter: { title: "Older Post" },
            content: "Check out [our homepage](/) for more info.",
          },
          {
            path: "news/2024-06-15-newer.md",
            frontmatter: { title: "Newer Post" },
            content: "Second post content.",
          },
          {
            path: "news/special.md",
            frontmatter: { title: "Tom and Jerry's Adventure" },
            content: "Special chars test",
          },
        ],
      });
      await site.build();
      feed = site.getOutput("feed.xml");
    });

    afterAll(() => site?.cleanup());

    // --- File Generation ---
    test("Feed XML file is generated by the build", () => {
      expect(site.hasOutput("feed.xml")).toBe(true);
    });

    // --- Atom XML Structure ---
    test("Feed is valid Atom XML", () => {
      expect(feed.includes('<?xml version="1.0"')).toBe(true);
      expect(feed.includes('<feed xmlns="http://www.w3.org/2005/Atom"')).toBe(
        true,
      );
      expect(feed.includes("</feed>")).toBe(true);
    });

    test("Feed contains required Atom elements", () => {
      expect(feed.includes("<title>")).toBe(true);
      expect(feed.includes("<id>")).toBe(true);
      expect(feed.includes("<updated>")).toBe(true);
      expect(feed.includes("<author>")).toBe(true);
    });

    test("Feed has self-referencing link", () => {
      expect(feed.includes('rel="self"')).toBe(true);
      expect(feed.includes("/feed.xml")).toBe(true);
    });

    // --- Entry Structure ---
    test("Feed contains entry elements for blog posts", () => {
      expect(feed.includes("<entry>")).toBe(true);
      expect(feed.includes("</entry>")).toBe(true);
      expect(feed.includes("Older Post")).toBe(true);
      expect(feed.includes("Newer Post")).toBe(true);
    });

    test("Feed entries have content with absolute URLs", () => {
      expect(feed.includes('<content type="html">')).toBe(true);
      // Links in content should be absolute (transformed by htmlBase plugin)
      expect(feed.includes('href="https://')).toBe(true);
    });

    test("Feed entries are ordered with most recent first", () => {
      const olderPos = feed.indexOf("Older Post");
      const newerPos = feed.indexOf("Newer Post");

      expect(olderPos > 0).toBe(true);
      expect(newerPos > 0).toBe(true);
      expect(newerPos < olderPos).toBe(true);
    });

    // --- Site Configuration ---
    test("Feed title matches configured site name", () => {
      expect(feed.includes("<title>Test Blog Name</title>")).toBe(true);
    });

    // --- Special Characters ---
    test("Feed is valid XML with special characters in titles", () => {
      expect(feed.includes("<entry>")).toBe(true);
      expect(feed.includes("Tom and Jerry")).toBe(true);
      // Apostrophe should be handled (either escaped or in CDATA)
      expect(feed.includes("Jerry's") || feed.includes("Jerry&#39;s")).toBe(
        true,
      );
    });
  });

  // --- Edge case: No posts site (needs separate build) ---
  describe("with no posts", () => {
    let site;
    let feed;

    beforeAll(async () => {
      site = await createTestSite({
        files: [
          {
            path: "pages/about.md",
            frontmatter: { title: "About", layout: "page" },
            content: "# About us",
          },
        ],
      });
      await site.build();
      feed = site.getOutput("feed.xml");
    });

    afterAll(() => site?.cleanup());

    test("Feed is generated even when there are no blog posts", () => {
      expect(site.hasOutput("feed.xml")).toBe(true);
      expect(feed.includes('<feed xmlns="http://www.w3.org/2005/Atom"')).toBe(
        true,
      );
      // With no posts, there should be no entries
      expect(!feed.includes("<entry>")).toBe(true);
    });
  });
});
