import { describe, test, expect } from "bun:test";
import { withTestSite } from "#test/test-site-factory.js";

// Test the actual feed output using isolated test sites
// Each test creates its own Eleventy build with specific content

describe("feed", () => {
  // --- File Generation ---
  test("Feed XML file is generated by the build", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "news/2024-01-01-test-post.md",
            frontmatter: { title: "Test Post" },
            content: "Test content for feed.",
          },
        ],
      },
      (site) => {
        expect(site.hasOutput("feed.xml")).toBe(true);
      },
    );
  });

  test("Feed is valid Atom XML", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "news/2024-01-01-test-post.md",
            frontmatter: { title: "Test Post" },
            content: "Test content.",
          },
        ],
      },
      (site) => {
        const content = site.getOutput("feed.xml");

        expect(content.includes('<?xml version="1.0"')).toBe(true);
        expect(content.includes('<feed xmlns="http://www.w3.org/2005/Atom"')).toBe(true);
        expect(content.includes("</feed>")).toBe(true);
      },
    );
  });

  test("Feed contains required Atom elements", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "news/2024-01-01-test-post.md",
            frontmatter: { title: "Test Post" },
            content: "Test content.",
          },
        ],
        config: { site_name: "Test Site" },
      },
      (site) => {
        const content = site.getOutput("feed.xml");

        expect(content.includes("<title>")).toBe(true);
        expect(content.includes("<id>")).toBe(true);
        expect(content.includes("<updated>")).toBe(true);
        expect(content.includes("<author>")).toBe(true);
      },
    );
  });

  // --- Entry Structure ---
  test("Feed contains entry elements for blog posts", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "news/2024-01-01-first-post.md",
            frontmatter: { title: "First Post" },
            content: "First post content.",
          },
          {
            path: "news/2024-01-02-second-post.md",
            frontmatter: { title: "Second Post" },
            content: "Second post content.",
          },
        ],
      },
      (site) => {
        const content = site.getOutput("feed.xml");

        expect(content.includes("<entry>")).toBe(true);
        expect(content.includes("</entry>")).toBe(true);
        expect(content.includes("First Post")).toBe(true);
        expect(content.includes("Second Post")).toBe(true);
      },
    );
  });

  test("Feed entries have content with absolute URLs", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "news/2024-01-01-test-post.md",
            frontmatter: { title: "Test Post" },
            content: "Check out [our homepage](/) for more info.",
          },
        ],
      },
      (site) => {
        const content = site.getOutput("feed.xml");

        expect(content.includes('<content type="html">')).toBe(true);
        // Links in content should be absolute (transformed by htmlBase plugin)
        expect(content.includes('href="https://')).toBe(true);
      },
    );
  });

  test("Feed has self-referencing link", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "news/2024-01-01-test-post.md",
            frontmatter: { title: "Test Post" },
            content: "Test content.",
          },
        ],
      },
      (site) => {
        const content = site.getOutput("feed.xml");

        expect(content.includes('rel="self"')).toBe(true);
        expect(content.includes("/feed.xml")).toBe(true);
      },
    );
  });

  // --- Edge Cases ---
  test("Feed is generated even when there are no blog posts", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "pages/about.md",
            frontmatter: { title: "About", layout: "page" },
            content: "# About us",
          },
        ],
      },
      (site) => {
        expect(site.hasOutput("feed.xml")).toBe(true);
        const feed = site.getOutput("feed.xml");
        expect(feed.includes('<feed xmlns="http://www.w3.org/2005/Atom"')).toBe(true);
        // With no posts, there should be no entries
        expect(!feed.includes("<entry>")).toBe(true);
      },
    );
  });

  test("Feed title matches configured site name", async () => {
    await withTestSite(
      {
        dataFiles: [
          {
            filename: "site.json",
            data: {
              name: "Test Blog Name",
              url: "https://test.example.com",
              description: "Test site",
            },
          },
        ],
        files: [
          {
            path: "news/hello.md",
            frontmatter: { title: "Hello World" },
            content: "First post",
          },
        ],
      },
      (site) => {
        const feed = site.getOutput("feed.xml");
        expect(feed.includes("<title>Test Blog Name</title>")).toBe(true);
      },
    );
  });

  test("Feed is valid XML with special characters in titles", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "news/special.md",
            frontmatter: { title: "Tom and Jerry's Adventure" },
            content: "Special chars test",
          },
        ],
      },
      (site) => {
        const feed = site.getOutput("feed.xml");
        // Feed should be valid XML and contain the entry
        expect(feed.includes("<entry>")).toBe(true);
        expect(feed.includes("Tom and Jerry")).toBe(true);
        // Apostrophe should be handled (either escaped or in CDATA)
        expect(feed.includes("Jerry's") || feed.includes("Jerry&#39;s")).toBe(true);
      },
    );
  });

  test("Feed entries are ordered with most recent first", async () => {
    await withTestSite(
      {
        files: [
          {
            path: "news/2024-01-01-older.md",
            frontmatter: { title: "Older Post" },
            content: "First",
          },
          {
            path: "news/2024-06-15-newer.md",
            frontmatter: { title: "Newer Post" },
            content: "Second",
          },
        ],
      },
      (site) => {
        const feed = site.getOutput("feed.xml");
        const olderPos = feed.indexOf("Older Post");
        const newerPos = feed.indexOf("Newer Post");

        expect(olderPos > 0).toBe(true);
        expect(newerPos > 0).toBe(true);
        expect(newerPos < olderPos).toBe(true);
      },
    );
  });
});
