media:
  input: src/images
  output: /images
  path: src/images
  categories:
    - image
settings:
  hide: true
  content:
    merge: true
content:
  - name: pages
    label: Pages
    path: src/pages
    type: collection
    subfolders: false
    view:
      fields:
        - permalink
        - meta_title
        - header_text
      primary: header_text
      sort:
        - header_text
    fields:
      - &a1
        name: header_image
        type: image
        label: Header Image
      - &a3
        name: header_text
        type: string
        label: Header Text
      - &a6
        name: subtitle
        type: string
        label: Subtitle
      - &a2
        name: body
        label: Body
        type: code
        options:
          language: markdown
      - &a4
        name: meta_title
        type: string
        label: Meta Title
        maxlength: 55
      - &a5
        name: meta_description
        type: string
        label: Meta Description
        maxlength: 155
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - name: key
            type: string
          - name: order
            type: number
          - name: url
            type: string
      - name: layout
        type: string
      - &a7
        name: permalink
        type: string
        label: Permalink
      - &a8
        name: redirect_from
        type: string
        label: Redirect From
        list: true
      - &a9
        name: faqs
        label: FAQs
        type: object
        list: true
        fields:
          - name: question
            type: string
            label: Question
            required: true
          - name: answer
            type: string
            label: Answer
            required: true
          - name: order
            type: number
            label: Order
      - &a10
        name: gallery
        type: image
        label: Gallery
        options:
          multiple: true
  - name: products
    label: Products
    path: src/products
    type: collection
    subfolders: false
    fields:
      - &a11
        name: title
        type: string
        label: Title
      - &a12
        name: thumbnail
        type: image
        label: Thumbnail
      - *a1
      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
          search: title
          value: "{path}"
          label: "{title}"
      - name: events
        label: Events
        type: reference
        options:
          collection: events
          multiple: true
          search: title
          value: "{path}"
          label: "{title}"
      - name: options
        label: Product Options
        type: object
        list: true
        fields:
          - name: name
            type: string
            label: Option Name
            required: true
          - name: max_quantity
            type: number
            label: Max Quantity
            default: 10
          - name: unit_price
            type: number
            label: Unit Price (£)
            required: true
          - name: days
            type: number
            label: Days (for hire products)
      - name: etsy_url
        label: Etsy URL
        type: string
      - *a2
      - &a14
        name: features
        type: string
        label: Features
        list: true
      - name: filter_attributes
        label: Filter Attributes
        type: object
        list: true
        fields:
          - name: name
            type: string
            label: Name
            required: true
          - name: value
            type: string
            label: Value
            required: true
      - *a3
      - *a4
      - *a5
      - *a6
      - *a7
      - *a8
      - *a9
      - *a10
      - &a15
        name: specs
        label: Specifications
        type: object
        list: true
        fields:
          - name: name
            type: string
            label: Name
            required: true
          - name: value
            type: string
            label: Value
            required: true
      - name: tabs
        label: Tabs
        type: object
        list: true
        fields:
          - name: title
            type: string
            label: Title
            required: true
          - name: body
            label: Body
            type: code
            options:
              language: markdown
            required: true
  - name: categories
    label: Categories
    path: src/categories
    type: collection
    subfolders: false
    filename: "{primary}.md"
    fields:
      - *a11
      - *a12
      - *a2
      - &a13
        name: featured
        type: boolean
        label: Featured
      - *a1
      - *a3
      - *a4
      - *a5
      - *a6
      - *a7
      - *a8
      - *a9
      - *a10
  - name: news
    label: News
    path: src/news
    type: collection
    subfolders: false
    fields:
      - *a11
      - *a1
      - name: date
        label: Date
        type: date
      - name: author
        label: Author
        type: reference
        options:
          collection: team
          multiple: false
          search: title
          value: "{path}"
          label: "{title}"
      - *a6
      - *a2
      - *a3
      - *a4
      - *a5
      - *a7
      - *a8
      - *a9
      - *a10
  - name: events
    label: Events
    path: src/events
    type: collection
    subfolders: false
    filename: "{primary}.md"
    view:
      fields:
        - title
        - event_date
        - recurring_date
        - event_location
      primary: title
      sort:
        - title
    fields:
      - *a12
      - *a1
      - *a11
      - *a6
      - name: event_date
        label: Event Date
        type: date
        required: false
      - name: recurring_date
        type: string
        label: Recurring Date (e.g. "Every Friday at 2 PM")
        required: false
      - name: event_location
        type: string
        label: Event Location
      - name: map_embed_src
        type: string
        label: Map Embed URL
        required: false
      - *a2
      - *a3
      - *a4
      - *a5
      - *a7
      - *a8
      - *a9
      - *a10
  - name: team
    label: Team
    path: src/team
    type: collection
    subfolders: false
    filename: "{primary}.md"
    fields:
      - *a11
      - *a12
      - name: snippet
        type: string
        label: Role
      - name: image
        type: image
        label: Profile Image
      - *a1
      - name: body
        label: Biography
        type: code
        options:
          language: markdown
      - *a7
      - *a8
      - *a9
      - *a10
  - name: reviews
    label: Reviews
    path: src/reviews
    type: collection
    subfolders: false
    fields:
      - &a16
        name: name
        type: string
        label: Name
      - name: url
        type: string
        label: URL
      - name: rating
        type: number
        label: Rating
      - name: thumbnail
        type: image
        label: Reviewer Photo
      - *a2
      - name: products
        label: Products
        type: reference
        options:
          collection: products
          multiple: true
          search: title
          value: "{path}"
          label: "{title}"
      - *a7
      - *a8
      - *a9
  - name: locations
    label: Locations
    path: src/locations
    type: collection
    subfolders: true
    filename: "{primary}.md"
    view:
      fields:
        - title
        - subtitle
      primary: title
      sort:
        - title
    fields:
      - *a11
      - *a12
      - *a6
      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
          search: title
          value: "{path}"
          label: "{title}"
      - *a4
      - *a5
      - *a2
      - *a7
      - *a8
      - *a9
      - *a10
  - name: properties
    label: Properties
    path: src/properties
    type: collection
    subfolders: false
    filename: "{primary}.md"
    view:
      fields:
        - title
        - subtitle
        - bedrooms
        - sleeps
      primary: title
      sort:
        - title
    fields:
      - *a11
      - *a6
      - *a12
      - *a1
      - *a13
      - name: locations
        label: Locations
        type: reference
        options:
          collection: locations
          multiple: true
          search: title
          value: "{path}"
          label: "{title}"
      - name: bedrooms
        type: number
        label: Bedrooms
      - name: bathrooms
        type: number
        label: Bathrooms
      - name: sleeps
        type: number
        label: Sleeps
      - name: price_per_night
        type: number
        label: Price Per Night
      - *a14
      - *a2
      - *a4
      - *a5
      - *a7
      - *a8
      - *a9
      - *a10
      - *a15
  - name: guides
    label: Guides
    path: src/guides
    type: collection
    subfolders: false
    filename: "{primary}.md"
    fields:
      - *a11
      - *a12
      - *a1
      - *a6
      - *a2
      - *a3
      - *a4
      - *a5
      - *a7
      - *a8
      - *a9
      - *a10
  - name: menus
    label: Menus
    path: src/menus
    type: collection
    subfolders: false
    fields:
      - *a11
      - *a12
      - &a17
        name: order
        type: number
        label: Order
      - *a1
      - *a6
      - *a2
      - *a4
      - *a5
      - *a7
      - *a8
      - *a9
      - *a10
  - name: menu-categories
    label: Menu Categories
    path: src/menu-categories
    type: collection
    subfolders: false
    fields:
      - *a16
      - *a12
      - *a17
      - name: menus
        label: Menus
        type: reference
        options:
          collection: menus
          multiple: true
          search: title
          value: "{path}"
          label: "{title}"
      - *a2
      - *a7
      - *a8
      - *a9
      - *a10
  - name: menu-items
    label: Menu Items
    path: src/menu-items
    type: collection
    subfolders: false
    fields:
      - *a16
      - *a12
      - name: price
        type: string
        label: Price
      - name: is_vegan
        type: boolean
        label: Is Vegan
      - name: is_gluten_free
        type: boolean
        label: Is Gluten Free
      - name: menu_categories
        label: Menu Categories
        type: reference
        options:
          collection: menu-categories
          multiple: true
          search: name
          value: "{path}"
          label: "{name}"
      - name: description
        type: string
        label: Description
      - *a2
      - *a7
      - *a8
      - *a9
      - *a10
  - name: snippets
    label: Snippets
    path: src/snippets
    type: collection
    subfolders: false
    filename: "{primary}.md"
    fields:
      - *a16
      - *a2
  - name: homepage
    label: Homepage Settings
    type: file
    path: src/_data/homepage.json
    fields:
      - name: show_products
        type: boolean
        label: Show Products Section
        default: true
      - name: show_menus
        type: boolean
        label: Show Menus Section
        default: true
      - name: show_news
        type: boolean
        label: Show News Section
        default: true
      - name: show_recurring_events
        type: boolean
        label: Show Recurring Events
        default: true
  - name: site
    label: Site Configuration
    type: file
    path: src/_data/site.json
    fields:
      - name: name
        type: string
        label: Site Name
      - name: url
        type: string
        label: Site URL
      - name: opening_times
        label: Opening Times
        type: object
        list: true
        fields:
          - name: day
            type: string
            label: Day
            required: true
          - name: hours
            type: string
            label: Hours
            required: true
      - name: socials
        label: Social Media Links
        type: object
        fields:
          - name: Github
            type: string
            label: Github
          - name: Forgejo
            type: string
            label: Forgejo
          - name: Facebook
            type: string
            label: Facebook
          - name: Instagram
            type: string
            label: Instagram
          - name: TikTok
            type: string
            label: TikTok
          - name: Google
            type: string
            label: Google
          - name: WhatsApp
            type: string
            label: WhatsApp
          - name: RSS
            type: string
            label: RSS
      - name: map_embed_src
        type: string
        label: Map Embed URL
  - name: meta
    label: Meta Configuration
    type: file
    path: src/_data/meta.json
    fields:
      - name: language
        type: string
        label: Language Code
        default: en-GB
      - name: organization
        label: Organization
        type: object
        fields:
          - name: description
            type: string
            label: Organization Description
          - name: legalName
            type: string
            label: Legal Name
          - name: foundingDate
            type: string
            label: Founding Date
          - name: founders
            label: Founders
            type: object
            list: true
            fields:
              - name: name
                type: string
                label: Name
          - name: address
            label: Address
            type: object
            fields:
              - name: streetAddress
                type: string
                label: Street Address
              - name: addressLocality
                type: string
                label: City
              - name: addressRegion
                type: string
                label: Region/State
              - name: postalCode
                type: string
                label: Postal Code
              - name: addressCountry
                type: string
                label: Country Code
          - name: contactPoint
            label: Contact Points
            type: object
            list: true
            fields:
              - name: telephone
                type: string
                label: Telephone
              - name: contactType
                type: string
                label: Contact Type
              - name: areaServed
                type: string
                label: Area Served
              - name: availableLanguage
                type: string
                label: Available Languages
                list: true
  - name: alt-tags
    label: Image Alt Tags
    type: file
    path: src/_data/alt-tags.json
    fields:
      - name: images
        type: object
        list: true
        fields:
          - name: path
            type: image
            label: Image
          - name: alt
            type: string
            label: Alt Text
